- name: Install catalogue component
  hosts: catalogue
  become: yes
  tasks:
    - name: Remove older Node.js versions
      ansible.builtin.dnf:
        name: nodejs
        state: absent

    - name: Enable Node.js 20 repo
      ansible.builtin.command:
        cmd: dnf module enable nodejs:20 -y

    - name: Install Node.js
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Check if roboshop user exists
      ansible.builtin.command:
        cmd: id roboshop
      register: out
      ignore_errors: true

    - name: Create roboshop user if not exists
      ansible.builtin.user:
        name: roboshop
      when: out.rc != 0

    - name: Check if /app directory exists
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: Create /app directory if not exists
      ansible.builtin.file:
        path: /app
        state: directory
      when: directory.stat.exists == False

    - name: Download the application code
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp

    - name: Unzip the downloaded application code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install application dependencies
      ansible.builtin.command:
        cmd: npm install
      args:
        chdir: /app

    - name: Set up the catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: true

    - name: Copy the MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB shell
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: installed

    - name: Load catalogue schema into MongoDB
      ansible.builtin.command:
        cmd: mongosh --host mongodb.joindevops.fun </app/schema/catalogue.js

    - name: Restart catalogue service
      ansible.builtin.service:
        name: catalogue
        state: restarted




    



     