- name: Install mysql component
  hosts: mysql
  become: yes
  tasks:
    - name: install mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: start mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: change the default root passowrd
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

    - name: check the new password working
      ansible.builtin.command: mysql
