- name: Create shipping component
  hosts: shipping
  become: yes
  tasks:
    - name: Install Maven
      ansible.builtin.dnf:
        name: maven
        state: installed

    - name: Check if roboshop user exists
      ansible.builtin.command:
        cmd: id roboshop
      register: output
      ignore_errors: true

    - name: Create roboshop user if not exists
      ansible.builtin.user:
        name: roboshop
      when: output.rc != 0

    - name: Check if /app directory exists
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: Create /app directory if not exists
      ansible.builtin.file:
        path: /app
        state: directory
      when: directory.stat.exists == False

    - name: Download the application code
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp/shipping.zip

    - name: Extract the application code
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: Build the application
      ansible.builtin.command:
        cmd: mvn clean package
      args:
        chdir: /app

    - name: Move the JAR file
      ansible.builtin.command:
        cmd: mv /app/target/shipping-1.0.jar /app/shipping.jar

    - name: Set up the shipping service
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and enable the shipping service
      ansible.builtin.service:
        name: shipping
        state: started
        enabled: true

    - name: Install MySQL client
      ansible.builtin.dnf:
        name: mysql
        state: installed

    - name: Load schema.sql
      ansible.builtin.shell:
        cmd: mysql -h mysql.joindevops.fun -uroot -pRoboShop@1 < /app/db/schema.sql

    - name: Load app-user.sql
      ansible.builtin.shell:
        cmd: mysql -h mysql.joindevops.fun -uroot -pRoboShop@1 < /app/db/app-user.sql

    - name: Load master-data.sql
      ansible.builtin.shell:
        cmd: mysql -h mysql.joindevops.fun -uroot -pRoboShop@1 < /app/db/master-data.sql

    - name: Restart the shipping service
      ansible.builtin.systemd:
        name: shipping
        state: restarted
