- name: creating shipping component
  hosts: shipping
  become: yes
  tasks:
    - name: install maven
      ansible.builtin.dnf:
        name: maven
        state: installed

    - name: check user exist or not
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true

    - when: output.rc!=0
      name: create user roboshop
      become: yes
      ansible.builtin.user:
        name: roboshop
        
    - name: check /app directory exists or not
      ansible.builtin.stat:
      path: /app
      register: directory

    - name: print the directory stats
      ansible.builtin.debug:
      msg: "output: {{directory}}"

    - when: directory.stat.exists == False
      name: create /app directory
      ansible.builtin.file:
      path: /app
      state: directory

    - name: download the application code
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp

    - name: unzip the downloaded file
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app

    - name: build the application
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app
    
    - name: moving the file
      ansible.builtin.copy:
        src: target/shipping-1.0.jar
        dest: shipping.jar

    - name: copy the shipping service
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: start the service
      ansible.builtin.service:
        name: shipping
        state: started
        enabled: true
    
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql
        state: installed

    - name: load schema of schema.sql
      ansible.builtin.command: mysql -h mysql.joindevops.fun -uroot -pRoboShop@1 < /app/db/schema.sql

    - name: load schema of app-user.sql 
      ansible.builtin.command: mysql -h mysql.joindevops.fun -uroot -pRoboShop@1 < /app/db/app-user.sql
      
    - name: load schema of master-data.sql
      ansible.builtin.command: mysql -h mysql.joindevops.fun -uroot -pRoboShop@1 < /app/db/master-data.sql

    - name: restart shipping
      ansible.builtin.systemd:
        name: shipping
        state: restarted