- name: Installing User Component
  hosts: user
  become: yes
  tasks:
    - name: Disable old Node.js module
      ansible.builtin.command:
        cmd: dnf module disable nodejs -y

    - name: Enable Node.js 20 module
      ansible.builtin.command:
        cmd: dnf module enable nodejs:20 -y

    - name: Install Node.js
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Check if roboshop user exists
      ansible.builtin.command:
        cmd: id roboshop
      register: output
      ignore_errors: true

    - name: Create roboshop user if not exists
      ansible.builtin.user:
        name: roboshop
      when: output.rc != 0

    - name: Check if /app directory exists
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: Create /app directory if not exists
      ansible.builtin.file:
        path: /app
        state: directory
      when: directory.stat.exists == False

    - name: Download the application code
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /tmp

    - name: Extract user artifact
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes

    - name: Install dependencies
      ansible.builtin.command:
        cmd: npm install
      args:
        chdir: /app

    - name: Set up user service
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and enable user service
      ansible.builtin.systemd:
        name: user
        state: started
        enabled: true

    - name: Copy MongoDB repo to yum.repos.d
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB shell
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: installed

    - name: load user data
      ansible.builtin.command: mongosh --host mongodb.joindevops.fun < /app/schema/user.js

    - name: restart user
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: true
