- name: Installing User Component
  #host should be checked
  hosts: user
  become: yes
  tasks:
    - name: disable node
      ansible.builtin.disable:
        name: node.js
        state: absent

    - name: enabling node
      #i have to check this here
      ansible.builtin.enable:
        name: nodejs:20
        state: enabled

    - name: installing node
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: check that user exist or not
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true

    - when: output.rc!=0
      name: create user roboshop
      become: yes
      ansible.builtin.user:
        name: roboshop

    - name: check /app directory exists or not
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: print the directory stats
      ansible.builtin.debug:
        msg: "output: {{directory}}"

    - when: directory.stat.exists == False
      name: create /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download the application code
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /tmp

    - name: extract user artifact
      ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

    - name: install dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: create user service
      ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

    - name: daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: start user service
      ansible.builtin.systemd:
        name: user
        state: started
        enabled: true

    - name: copy mongo repo to yum.repos.d
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb-mongosh
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: installed
    
    - name: load schema 
      ansible.builtin.command: mongosh --host mongodb.joindevops.fun </app/schema/user.js